version: '3'
services:
  vault:
    container_name: elms-vault
    image: vault:1.13.3
    environment:
      VAULT_ADDR: http://127.0.0.1:8200
    ports:
      - "8200:8200"
    volumes:
      - vault-volume:/vault/file:rw
      - ./vault/vault.json:/vault/config/vault.json:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json

  db:
    image: postgres:latest
    container_name: elms-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_MULTIPLE_DATABASES="order_db","auth_user_db","payment_db","delivery_db","inventory_db"
      - POSTGRES_USER=postgre_user
      - POSTGRES_PASSWORD=postgre_secret_password
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - database-data:/var/lib/postgresql/data/

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: elms-zookeeper
    ports:
      - "2181:2181"
    restart: on-failure

  kafka-0:
    image: wurstmeister/kafka
    container_name: elms-kafka-0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: elms-zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://elms-kafka-0:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - kafka-0-volume:/data
    restart: on-failure

  kafka-1:
    image: wurstmeister/kafka
    container_name: elms-kafka-1
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: elms-zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29093,EXTERNAL://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://elms-kafka-1:29093,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - kafka-1-volume:/data
    restart: on-failure

  kafka-ui:
    container_name: elms-kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: elms-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: elms-kafka-0:29092, elms-kafka-1:29093
    depends_on:
      - kafka-0

  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:3.3
    container_name: elms-zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"

volumes:
  database-data:
  kafka-0-volume:
  kafka-1-volume:
